---
- name: Ansible Deployment on target machines present in inventory file.
  hosts: all
  tasks:
    - name: Pull insti-lunchbox-backend devops image
      docker_image:
        name: aadarsh96/insti-lunchbox-backend:latest
        source: pull

    - name: Prune previous Docker Images and container
      shell: "docker system prune -f"
      
    - name: deploy insti-lunchbox composed docker container
      shell: "docker compose up -d --build"
...
