---
- name: Ansible Deployment on target machines present in inventory file.
  hosts: all
  tasks:
  
    - name: Prune previous Docker Images and container
      shell: "docker compose pull clientnode"
      
    - name: Pull
      shell: "docker compose pull app"
      
    - name: Prune previous Docker Images and container
      shell: "docker system prune -f"
      
    - name: deploy insti-lunchbox composed docker container
      shell: "docker compose up -d --build"
...
