---
- name: Ansible Deployment on target machines present in inventory file.
  hosts: all
  tasks:
    # - name: Stop Docker container
    #   docker_container:
    #     name: spe-calc
    #     state: stopped

    # - name: Remove Docker container
    #   docker_container:
    #     name: spe-calc
    #     state: absent

    # - name: Remove Docker image
    #   docker_image:
    #     state: absent
    #     name: aadarsh96/spe-calc
    #     tag: latest

    - name: Pull insti-lunchbox-backend devops image
      docker_image:
        name: aadarsh96/insti-lunchbox-backend:latest
        source: pull

    - name: deploy insti-lunchbox-backend docker container
        sh: "docker run -d -p 9090:9090 --name insti-lunchbox-backend aadarsh96/insti-lunchbox-backend:latest"
...